### ISSUE TITLE
statistic value

### ISSUE THREAD

**Issue by hsolbrig** [ebmonfhir/fhir#5]
Currently, the name of the statistic value is `quantity`.  Would it make more sense as `value`?

**Comment by Khalid-Shahin** [comment]
We decided at some point that quantity would be more encompassing since it has comparator. Right now in our Artur's Evidence example it isn't really showing how this can be used since we have "0.041" and comparator is "=", but in another instance we could have "5" and ">" to describe values greater than 5.
